package dev.jjcoll.distributedtaskviz.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDateTime;

/**
 * Data Transfer Object (DTO) for Task responses.
 * This record is used to send task data to API clients.
 * Records are immutable, providing thread-safety and automatic generation of:
 * - Constructor with all fields
 * - Getters (accessor methods)
 * - equals(), hashCode(), and toString()
 */
@Schema(description = "Response object containing task information")
public record TaskResponseDTO(
        /**
         * The unique identifier for the task.
         * Auto-generated by the database when a task is created.
         */
        @Schema(description = "Unique identifier of the task", example = "1")
        Long id,

        /**
         * The name or description of the task.
         */
        @Schema(description = "Name/description of the task", example = "Process user data")
        String name,

        /**
         * The current status of the task.
         * Common values: PENDING, RUNNING, COMPLETED, FAILED
         */
        @Schema(description = "Current status of the task", example = "PENDING")
        String status,

        /**
         * Timestamp when the task was created.
         */
        @Schema(description = "Timestamp when the task was created", example = "2025-10-08T14:30:00")
        LocalDateTime createdAt,

        /**
         * Timestamp when the task was completed.
         * This will be null if the task hasn't completed yet.
         */
        @Schema(description = "Timestamp when the task was completed (null if not completed)", example = "2025-10-08T14:35:00", nullable = true)
        LocalDateTime completedAt
) {}
