package dev.jjcoll.distributedtaskviz.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDateTime;

/**
 * Data Transfer Object (DTO) for Task responses.
 * This POJO is used to send task data to API clients.
 * It includes all task information including the auto-generated ID.
 */
@Schema(description = "Response object containing task information")
public class TaskResponse {

    /**
     * The unique identifier for the task.
     * This is auto-generated by the database when a task is created.
     */
    @Schema(description = "Unique identifier of the task", example = "1")
    private Long id;

    /**
     * The name or description of the task.
     */
    @Schema(description = "Name/description of the task", example = "Process user data")
    private String name;

    /**
     * The current status of the task.
     * Common values: PENDING, RUNNING, COMPLETED, FAILED
     */
    @Schema(description = "Current status of the task", example = "PENDING")
    private String status;

    /**
     * Timestamp when the task was created.
     */
    @Schema(description = "Timestamp when the task was created", example = "2025-10-08T14:30:00")
    private LocalDateTime createdAt;

    /**
     * Timestamp when the task was completed.
     * This will be null if the task hasn't completed yet.
     */
    @Schema(description = "Timestamp when the task was completed (null if not completed)", example = "2025-10-08T14:35:00", nullable = true)
    private LocalDateTime completedAt;

    // Default constructor
    public TaskResponse() {
    }

    // Full constructor
    public TaskResponse(Long id, String name, String status, LocalDateTime createdAt, LocalDateTime completedAt) {
        this.id = id;
        this.name = name;
        this.status = status;
        this.createdAt = createdAt;
        this.completedAt = completedAt;
    }

    // Getters and Setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getCompletedAt() {
        return completedAt;
    }

    public void setCompletedAt(LocalDateTime completedAt) {
        this.completedAt = completedAt;
    }
}
