package dev.jjcoll.distributedtaskviz.mappers;

import dev.jjcoll.distributedtaskviz.dto.TaskResponseDTO;
import dev.jjcoll.distributedtaskviz.dto.TaskSubmissionRequestDTO;
import dev.jjcoll.distributedtaskviz.model.Task;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

/**
 * MapStruct mapper for converting between Task entities and DTOs.
 * The @Mapper annotation tells MapStruct to generate an implementation of this interface
 * at compile time. The componentModel = "spring" makes it a Spring bean that can be
 * injected into other components.
 * MapStruct will automatically generate the implementation code in the target/generated-sources
 * directory during compilation.
 */
@Mapper(componentModel = "spring")
public interface TaskMapper {

    /**
     * Converts a Task entity to a TaskResponse DTO.
     * Used when returning task data from the API.
     * MapStruct automatically maps fields with matching names:
     * - Task.id -> TaskResponse.id
     * - Task.name -> TaskResponse.name
     * - Task.status -> TaskResponse.status
     * - Task.createdAt -> TaskResponse.createdAt
     * - Task.completedAt -> TaskResponse.completedAt
     *
     * @param task The Task entity from the database
     * @return TaskResponse DTO for the API response
     */
    TaskResponseDTO toDto(Task task);

    /**
     * Converts a TaskSubmissionRequest DTO to a Task entity.
     * Used when creating a new task from API input.
     * The @Mapping annotations handle fields that don't match or need special handling:
     * - id is ignored (auto-generated by database)
     * - createdAt is set to current time via expression
     * - status is set to "PENDING" as default
     * - completedAt is ignored (null until task completes)
     * - name is automatically mapped from the request
     *
     * @param request The TaskSubmissionRequest from the API
     * @return Task entity ready to be persisted
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "createdAt", expression = "java(java.time.LocalDateTime.now())")
    @Mapping(target = "status", constant = "PENDING")
    @Mapping(target = "completedAt", ignore = true)
    Task toEntity(TaskSubmissionRequestDTO request);
}