package dev.jjcoll.distributedtaskviz.mappers;

import dev.jjcoll.distributedtaskviz.dto.WorkerCreateRequestDTO;
import dev.jjcoll.distributedtaskviz.dto.WorkerResponseDTO;
import dev.jjcoll.distributedtaskviz.model.Worker;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

/**
 * MapStruct mapper for converting between Worker entities and DTOs.
 * The @Mapper annotation tells MapStruct to generate an implementation of this interface
 * at compile time. The componentModel = "spring" makes it a Spring bean that can be
 * injected into other components.
 * MapStruct will automatically generate the implementation code in the target/generated-sources
 * directory during compilation.
 */
@Mapper(componentModel = "spring")
public interface WorkerMapper {

    /**
     * Converts a Worker entity to a WorkerResponseDTO.
     * Used when returning worker data from the API.
     * MapStruct automatically maps fields with matching names:
     * - Worker.id -> WorkerResponseDTO.id
     * - Worker.name -> WorkerResponseDTO.name
     * - Worker.status -> WorkerResponseDTO.status
     * - Worker.createdAt -> WorkerResponseDTO.createdAt
     * - Worker.lastHeartbeat -> WorkerResponseDTO.lastHeartbeat
     *
     * @param worker The Worker entity from the database
     * @return WorkerResponseDTO for the API response
     */
    WorkerResponseDTO toDto(Worker worker);

    /**
     * Converts a WorkerCreateRequestDTO to a Worker entity.
     * Used when creating a new worker from API input.
     * The @Mapping annotations handle fields that don't match or need special handling:
     * - id is ignored (auto-generated by database)
     * - createdAt is set to current time via expression
     * - status is set to "IDLE" as default
     * - lastHeartbeat is set to current time via expression
     * - name is mapped from the request (can be null for auto-generation)
     *
     * @param request The WorkerCreateRequestDTO from the API
     * @return Worker entity ready to be persisted
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "createdAt", expression = "java(java.time.LocalDateTime.now())")
    @Mapping(target = "status", expression = "java(dev.jjcoll.distributedtaskviz.model.WorkerStatus.IDLE)")
    @Mapping(target = "lastHeartbeat", expression = "java(java.time.LocalDateTime.now())")
    Worker toEntity(WorkerCreateRequestDTO request);
}