package dev.jjcoll.distributedtaskviz;

import com.fasterxml.jackson.databind.ObjectMapper;
import dev.jjcoll.distributedtaskviz.dto.WorkerCreateRequestDTO;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.transaction.annotation.Transactional;

import static org.hamcrest.Matchers.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultHandlers.print;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

/**
 * Integration tests for WorkerController endpoints.
 *
 * @ActiveProfiles("test") activates the "test" profile, which prevents the DataSeeder
 * from running (it has @Profile("!test")). This ensures tests start with an empty database.
 *
 * @Transactional ensures test isolation by wrapping each test method in a transaction
 * that is automatically rolled back after the test completes. This means:
 * - Each test starts with a clean database state
 * - Data created in one test doesn't affect other tests
 * - No manual cleanup needed between tests
 * - Much faster than recreating the Spring context (@DirtiesContext)
 */
@SpringBootTest
@AutoConfigureMockMvc
@ActiveProfiles("test")
@Transactional
public class WorkerControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @Test
    void testCreateWorker_WithName() throws Exception {
        // Arrange
        WorkerCreateRequestDTO request = new WorkerCreateRequestDTO("custom-worker");

        // Act & Assert
        mockMvc.perform(post("/api/workers")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.id").exists())
                .andExpect(jsonPath("$.name", is("custom-worker")))
                .andExpect(jsonPath("$.status", is("IDLE")))
                .andExpect(jsonPath("$.createdAt").exists())
                .andExpect(jsonPath("$.lastHeartbeat").exists())
                .andDo(print());
    }

    @Test
    void testCreateWorker_WithoutName_AutoGenerated() throws Exception {
        // Act & Assert: First worker should be named "worker-1"
        mockMvc.perform(post("/api/workers")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{}"))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.name", is("worker-1")))
                .andExpect(jsonPath("$.status", is("IDLE")))
                .andDo(print());

        // Create second worker - should be "worker-2"
        mockMvc.perform(post("/api/workers")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{}"))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.name", is("worker-2")))
                .andExpect(jsonPath("$.status", is("IDLE")))
                .andDo(print());
    }

    @Test
    void testCreateWorker_WithEmptyRequestBody() throws Exception {
        // Act & Assert: Empty body should auto-generate name
        mockMvc.perform(post("/api/workers")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(""))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.name", startsWith("worker-")))
                .andExpect(jsonPath("$.status", is("IDLE")))
                .andDo(print());
    }

    @Test
    void testCreateWorker_WithNullName() throws Exception {
        // Arrange
        WorkerCreateRequestDTO request = new WorkerCreateRequestDTO(null);

        // Act & Assert
        mockMvc.perform(post("/api/workers")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.name", startsWith("worker-")))
                .andExpect(jsonPath("$.status", is("IDLE")))
                .andDo(print());
    }

    @Test
    void testGetWorker_Success() throws Exception {
        // Arrange: Create a worker first
        WorkerCreateRequestDTO request = new WorkerCreateRequestDTO("test-worker");
        String responseJson = mockMvc.perform(post("/api/workers")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isCreated())
                .andReturn()
                .getResponse()
                .getContentAsString();

        Long workerId = objectMapper.readTree(responseJson).get("id").asLong();

        // Act & Assert: Retrieve the worker by ID
        mockMvc.perform(get("/api/workers/" + workerId))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.id", is(workerId.intValue())))
                .andExpect(jsonPath("$.name", is("test-worker")))
                .andExpect(jsonPath("$.status", is("IDLE")))
                .andDo(print());
    }

    @Test
    void testGetWorker_NotFound() throws Exception {
        // Try to get a worker with an ID that doesn't exist
        Long nonExistentId = 99999L;

        mockMvc.perform(get("/api/workers/" + nonExistentId))
                .andExpect(status().isNotFound())
                .andDo(print());
    }

    @Test
    void testGetAllWorkers_Empty() throws Exception {
        // Act & Assert: Should return empty list
        mockMvc.perform(get("/api/workers"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$").isArray())
                .andExpect(jsonPath("$.length()", is(0)))
                .andDo(print());
    }

    @Test
    void testGetAllWorkers_MultipleWorkers() throws Exception {
        // Arrange: Create multiple workers
        createWorker("worker-alpha");
        createWorker("worker-beta");
        createWorker("worker-gamma");

        // Act & Assert
        mockMvc.perform(get("/api/workers"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$").isArray())
                .andExpect(jsonPath("$.length()", is(3)))
                .andExpect(jsonPath("$[*].name", containsInAnyOrder("worker-alpha", "worker-beta", "worker-gamma")))
                .andExpect(jsonPath("$[*].status", everyItem(is("IDLE"))))
                .andDo(print());
    }

    @Test
    void testStopWorker_Success() throws Exception {
        // Arrange: Create a worker
        WorkerCreateRequestDTO request = new WorkerCreateRequestDTO("worker-to-stop");
        String responseJson = mockMvc.perform(post("/api/workers")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isCreated())
                .andReturn()
                .getResponse()
                .getContentAsString();

        Long workerId = objectMapper.readTree(responseJson).get("id").asLong();

        // Act & Assert: Stop the worker
        mockMvc.perform(delete("/api/workers/" + workerId))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.id", is(workerId.intValue())))
                .andExpect(jsonPath("$.name", is("worker-to-stop")))
                .andExpect(jsonPath("$.status", is("STOPPED")))
                .andDo(print());

        // Verify the worker status was updated
        mockMvc.perform(get("/api/workers/" + workerId))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.status", is("STOPPED")))
                .andDo(print());
    }

    @Test
    void testStopWorker_NotFound() throws Exception {
        // Try to stop a worker that doesn't exist
        Long nonExistentId = 99999L;

        mockMvc.perform(delete("/api/workers/" + nonExistentId))
                .andExpect(status().isNotFound())
                .andDo(print());
    }

    @Test
    void testWorkerLifecycle() throws Exception {
        // 1. Create a worker
        WorkerCreateRequestDTO createRequest = new WorkerCreateRequestDTO("lifecycle-worker");
        String createResponse = mockMvc.perform(post("/api/workers")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(createRequest)))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.name", is("lifecycle-worker")))
                .andExpect(jsonPath("$.status", is("IDLE")))
                .andReturn()
                .getResponse()
                .getContentAsString();

        Long workerId = objectMapper.readTree(createResponse).get("id").asLong();

        // 2. Retrieve the worker
        mockMvc.perform(get("/api/workers/" + workerId))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.status", is("IDLE")))
                .andDo(print());

        // 3. Verify it appears in list
        mockMvc.perform(get("/api/workers"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$[*].id", hasItem(workerId.intValue())))
                .andDo(print());

        // 4. Stop the worker
        mockMvc.perform(delete("/api/workers/" + workerId))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.status", is("STOPPED")))
                .andDo(print());

        // 5. Verify status was updated
        mockMvc.perform(get("/api/workers/" + workerId))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.status", is("STOPPED")))
                .andDo(print());
    }

    @Test
    void testMultipleWorkersAutoGeneration() throws Exception {
        // Create 5 workers without names
        for (int i = 1; i <= 5; i++) {
            mockMvc.perform(post("/api/workers")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("{}"))
                    .andExpect(status().isCreated())
                    .andExpect(jsonPath("$.name", is("worker-" + i)))
                    .andDo(print());
        }

        // Verify all 5 workers exist
        mockMvc.perform(get("/api/workers"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.length()", is(5)))
                .andExpect(jsonPath("$[*].name", containsInAnyOrder(
                        "worker-1", "worker-2", "worker-3", "worker-4", "worker-5"
                )))
                .andDo(print());
    }

    @Test
    void testMixedWorkerCreation() throws Exception {
        // Create auto-generated worker
        mockMvc.perform(post("/api/workers")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{}"))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.name", is("worker-1")))
                .andDo(print());

        // Create custom-named worker
        WorkerCreateRequestDTO customRequest = new WorkerCreateRequestDTO("custom-worker");
        mockMvc.perform(post("/api/workers")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(customRequest)))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.name", is("custom-worker")))
                .andDo(print());

        // Create another auto-generated worker - should be worker-2
        mockMvc.perform(post("/api/workers")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{}"))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.name", is("worker-2")))
                .andDo(print());

        // Verify all three workers
        mockMvc.perform(get("/api/workers"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.length()", is(3)))
                .andExpect(jsonPath("$[*].name", containsInAnyOrder(
                        "worker-1", "worker-2", "custom-worker"
                )))
                .andDo(print());
    }

    // Helper method to create workers
    private void createWorker(String name) throws Exception {
        WorkerCreateRequestDTO request = new WorkerCreateRequestDTO(name);
        mockMvc.perform(post("/api/workers")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isCreated());
    }
}